name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel ongoing builds
        uses: styfle/cancel-workflow-action@0.9.0

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Download dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
        env:
          HUSKY_SKIP_INSTALL: true

      - name: Run validation script
        run: npm run validate

      - name: Run build script
        run: npm run build
